# Created with Winget Automation
PackageIdentifier: IrshadAli.SIARMessenger
PackageVersion: 0.1.0
PackageName: SIAR Messenger
Publisher: Irshad Ali
License: Apache-2.0
ShortDescription: Survivable Identity & Autonomous Routing Mesh Desktop Client
PackageUrl: https://siar.irshad.org.in
Installers:
  - Architecture: x64
    InstallerType: msix
    InstallerUrl: https://pkg.siar.irshad.org.in/releases/SIAR_Messenger-0.1.0-x64.msix
    InstallerSha256: ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb
ManifestType: singleton
ManifestVersion: 1.6.0
